name: Deploy PROD

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -f devops/Dockerfile -t djyoo-be-prod:latest .

      - name: Save Docker image
        run: |
          docker save djyoo-be-prod:latest | gzip > djyoo-be-prod.tar.gz

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 222
          source: "djyoo-be-prod.tar.gz"
          target: "/srv/docker"

      - name: Deploy container on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 222
          script: |
            mkdir -p /srv/docker
            docker load < /srv/docker/djyoo-be-prod.tar.gz

            docker stop ${{ secrets.PROD_CONTAINER_NAME }} || true
            docker rm ${{ secrets.PROD_CONTAINER_NAME }} || true

            docker run -d \
              --name ${{ secrets.PROD_CONTAINER_NAME }} \
              -e SPRING_PROFILES_ACTIVE=prod \
              -p ${{ secrets.PROD_PORT }}:8080 \
              --restart unless-stopped \
              djyoo-be-prod:latest
